name = "cf-redirector-w3do"
main = "src/index.ts"
compatibility_date = "2023-08-17"
workers_dev = false
route = { pattern = "w3.do/*", zone_name = "w3.do" }

kv_namespaces = [
  { binding = "NOSTR_REDIRECT_KV_CACHE", id = "775fdfdfe3b74ccc95d61a907f4ce3ea" }
]

[placement]
mode = "smart"

[vars]
NOSTR_RELAYS = "wss://relay.damus.io,wss://relay.nostr.band,wss://nos.lol,wss://nostr.wine"